#!/bin/bash 

# This file is part of Centreon-Discovery module.
#
# Centreon-Discovery is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses>.
#
# Module name: Centreon-Discovery
#
# First developpement by: Jean Marc Grisard - Christophe Coraboeuf
# Adaptation for Centreon 2.0 by: Merethis team
# Inspired from Watt's script.
#
# Modified by: Sub2.13
#
# WEBSITE: http://community.centreon.com/projects/centreon-discovery
# SVN: http://svn.modules.centreon.com/centreon-discovery

#---------------------#
# Used by install.sh  #
#---------------------#

## load all functions used in this script
. $INSTALL_DIR/variables
. $INSTALL_DIR/display_functions

######### FOR BINARIES #########

#----
## define a specific variables for grep,cat,sed,... binaries
## This functions was been use in first line on your script
## @return 0	All is't ok
## @return 1	problem with one variable
## @Globals	GREP, CAT, SED, CHMOD, CHOWN, PYTHON, NMAP, GCC
#----
function define_specific_binary_vars() {
    local vars_bin="GREP CAT SED CHMOD CHOWN PYTHON NMAP GCC DPKG YUM"
    local var_bin_tolower=""
    for var_bin in $vars_bin ; 
    do
	if [ -z $(eval echo \$$var_bin) ] ; then
	    var_bin_tolower="$(echo $var_bin | tr [:upper:] [:lower:])"
	    pathfind_ret "$var_bin_tolower" "$(echo -n $var_bin)"
	    if [ "$?" -eq 0 ] ; then
		eval "$var_bin='$(eval echo \$$var_bin)/$var_bin_tolower'"
		export $(echo $var_bin)
		log "INFO" "$var_bin=$(eval echo \$$var_bin)"
	    else
		eval "$var_bin=$var_bin_tolower"
		export $(echo $var_bin)
#		    return 1
	    fi
	fi
    done
    return 0
}


#----
## find in $PATH if binary exist
## @param	file to test
## @return 0	found
## @return 1	not found
## @Globals	PATH
#----
function pathfind() {
    OLDIFS="$IFS"
    IFS=:
    for p in $PATH; do
	if [ -x "$p/$*" ]; then
	    IFS="$OLDIFS"
	    return 0
	fi
    done
    IFS="$OLDIFS"
    return 1
}

#----
## find in $PATH if binary exist and return dirname
## @param	file to test
## @param	global variable to set a result
## @return 0	found
## @return 1	not found
## @Globals	PATH
#----
function pathfind_ret() {
    local bin=$1
    local var_ref=$2
    local OLDIFS="$IFS"
    IFS=:
    for p in $PATH; do
	if [ -x "$p/$bin" ]; then
	    IFS="$OLDIFS"
	    eval $var_ref=$p
	    return 0
	fi
    done
    IFS="$OLDIFS"
    return 1
}

######### GET_XXXXXX #########

#---
## {Get Centreon install dir and user/group for apache}
#----
function get_centreon_parameters() {
    INSTALL_DIR_CENTREON=`${CAT} $CENTREON_CONF/$FILE_CONF | ${GREP} "INSTALL_DIR_CENTREON" | cut -d '=' -f2`;
    WEB_USER=`${CAT} $CENTREON_CONF/$FILE_CONF | ${GREP} "WEB_USER" | cut -d '=' -f2`;
    WEB_GROUP=`${CAT} $CENTREON_CONF/$FILE_CONF | ${GREP} "WEB_GROUP" | cut -d '=' -f2`;
    NAGIOS_PLUGIN=`${CAT} $CENTREON_CONF/$FILE_CONF | ${GREP} "NAGIOS_PLUGIN" | cut -d '=' -f2`;
    NAGIOS_USER=`${CAT} $CENTREON_CONF/$FILE_CONF | ${GREP} "NAGIOS_USER" | cut -d '=' -f2`;
    NAGIOS_GROUP=`${CAT} $CENTREON_CONF/$FILE_CONF | ${GREP} "NAGIOS_GROUP" | cut -d '=' -f2`;
    DB_NAME_CENTREON=`${CAT} $CENTREON_CONF/$FILE_CONF_CENT | grep "\$conf_centreon\['db'\]" | cut -d '=' -f2 | ${SED} -e s/\"//g -e s/\ //g -e s/\;//g`
    INIT_D=`${CAT} $CENTREON_CONF/$FILE_CONF_CENTPLUGIN | grep "INIT_D" | cut -d '=' -f2`
    
    if [ "$INSTALL_DIR_CENTREON" != "" ] && [ "$WEB_USER" != "" ] && [ "$WEB_GROUP" != "" ] && [ "$NAGIOS_PLUGIN" != "" ] && [ "$NAGIOS_USER" != "" ] && [ "$NAGIOS_GROUP" != "" ] && [ "DB_NAME_CENTREON" != "" ] && [ "$INIT_D" != "" ]; then
	return 0;
    else
	return 1;
    fi
}

#---
## {Get location of instCentWeb.conf file}
##
## @Stdout Error message if user set incorrect directory
## @Stdin Path with must contain $FILE_CONF
#----
function get_centreon_configuration_location() {
    write_header "Load Centreon parameters" ""

    err=1
    while [ $err != 0 ]
    do
	echo -e "Please specify the directory with contain \"$FILE_CONF\" [$CENTREON_CONF]"
	echo -n "> "
	read temp_read
	
	if [ -z $temp_read ]; then
	    temp_read=$CENTREON_CONF
                    #echo_failure "The directory does not exist!" "$fail"
	fi
	
	if [ -d $temp_read ] && [ -f $temp_read/$FILE_CONF ] ; then
	    err=0
	    CENTREON_CONF=$temp_read
	else
	    echo_failure "File \"$FILE_CONF\" does not exist in this directory!" "$fail"
	fi
    done
}

#---
## {Get location of instCentWeb.conf file}
##
## @Stdout Error message if user set incorrect directory
## @Stdin Path with must contain $FILE_CONF
#----
function get_agent_install_directory_location() {
    err=1
    while [ $err != 0 ]
    do
	echo -e "Where do you want to install Discovery Agent ? [$AGENT_DIR]"
	echo -n "> "
	read temp_read
	echo ""
	if [ -z $temp_read ]; then
	    temp_read=$AGENT_DIR
	    err=0
	fi
	
	if [ -d $temp_read ] ; then
	    yes_no_default "The directory exist. Do you want to overwrite it?"
	    if [ "$?" -eq 0 ] ; then
		err=0
		AGENT_DIR=$temp_read
	    else
		err=1
	    fi
	else
	    if [ ${temp_read:0:1} == "/" ] ; then
		err=0
		AGENT_DIR=$temp_read
	    else
		echo "Directory \"$temp_read\" is not valid!"
		err=1
	    fi
	fi
    done
    if [ "$AGENT_DIR" != "" ] ; then
	return 0;
    else
	return 1;
    fi
}

#----
## install modules Python in function $TYPE_INSTALL (poller, central, both)
##
## @return 0 if all install is ok
## @return 1 if any install is ko
## @Stderr Log into $LOG_FILE
#----
function install_modPython() {
#    write_header "Install Python modules"

    echo -ne "Module PyCrypto ..."
    cd $BASE_DIR/modPython/pycrypto-2.5
    ${PYTHON} setup.py install >> $LOG_FILE 2>&1
    install_ok=$?
    display_return "$install_ok" "Module PyCrypto"
    if [ $install_ok -ne 0 ] ; then
	return 1
    fi
   
    case $TYPE_INSTALL in
	poller )
	    echo -ne "Module NMAP ..."
	    cd $BASE_DIR/modPython/python-nmap-0.1.4
	    ${PYTHON} setup.py install >> $LOG_FILE 2>&1
	    install_ok=$?
	    display_return "$install_ok" "Module NMAP"
	    return $install_ok
	    ;;
	central ) 
	    echo -n "Module SetupTools ..."
	    cd $BASE_DIR/modPython/setuptools-0.6c11
	    ${PYTHON} setup.py install >> $LOG_FILE 2>&1
	    install_ok_1=$?
            display_return "$install_ok_1" "Module SetupTools"
	    echo -n "Module MySQLdb ..."
	    cd $BASE_DIR/modPython/MySQL-python-1.2.3
	    ${PYTHON} setup.py install >> $LOG_FILE 2>&1
	    install_ok_2=$?
	    display_return "$install_ok_2" "Module MySQLdb"
	    return $(($install_ok_1+$install_ok_2))
	    ;;
	both ) 
	    echo -ne "Module NMAP ..."
            cd $BASE_DIR/modPython/python-nmap-0.1.4
	    ${PYTHON} setup.py install >> $LOG_FILE 2>&1
	    install_ok_1=$?
	    display_return "$install_ok_1" "Module NMAP"
            echo -ne "Module SetupTools ..."
	    cd $BASE_DIR/modPython/setuptools-0.6c11
	    ${PYTHON} setup.py install >> $LOG_FILE 2>&1
	    install_ok_2=$?
	    display_return "$install_ok_2" "Module SetupTools"
	    echo -ne "Module MySQLdb ..."
            cd $BASE_DIR/modPython/MySQL-python-1.2.3
	    ${PYTHON} setup.py install >> $LOG_FILE 2>&1
	    install_ok_3=$?
	    display_return "$install_ok_3" "Module MySQLdb"
	    return $(($install_ok_1+$install_ok_2+$install_ok_3))
	    ;;
	* )
	    ;;
    esac
}

######### INSTALL_XXXXXX #########

#----
## (Install security on agent)
##
## @param         
## @return 0      install security ok
## @return 1      install security fail
#----
install_security_agent() {
   local key="" key2="." tmp="" file=""
   
   if [ $UPDATE -eq 1 ]; then
       yes_no_default "Do you want to secure exchanges between agents?"
       tmp=$?
       SECURE=$tmp
   else
       tmp=$SECURE
       key=$KEY
   fi
   
   if [ $tmp -eq 0 ]; then
       if [ $UPDATE -eq 1 ]; then
	   while [ "$key" != "$key2" ]
	   do
	       echo -e "Please specify the shared secret key []"
	       echo -n "> "
	       read -s key
	       echo -e "\nConfirm the shared secret key []"
	       echo -n "> "
	       read -s key2
	       echo -e "\n"
	       if [ "$key" != "$key2" ] ; then
		   echo -e "Sorry, keys do not match !"
	       fi
	   done
	   key=$(echo -n "$key" | md5sum | awk '{print $1}')
       fi
       echo -n "Configuring secret key for "
       case $TYPE_INSTALL in
	   poller )
	       echo -n "poller agent"
	       file="DiscoveryAgent_poller.py"
	       $SED -i -e 's|@KEY@|'"$key"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1	
	       display_return "$?" "Configuring secret key for DiscoveryAgent_poller.py"
	       ;;
	   central )
	       echo -n "central agent"
	       file="DiscoveryAgent_central.py"
	       $SED -i -e 's|@KEY@|'"$key"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1	
	       display_return "$?" "Configuring secret key for DiscoveryAgent_central.py"
	       ;;
	   both )
	       echo -n "poller and central agents"
	       file="DiscoveryAgent_poller.py"
	       $SED -i -e 's|@KEY@|'"$key"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1	
	       file="DiscoveryAgent_central.py"
	       $SED -i -e 's|@KEY@|'"$key"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1	
	       display_return "$?" "Configuring secret key for DiscoveryAgent_central.py"
	       ;;
	   * )
	       ;;
       esac
       return 0
   else
       key=""
       case $TYPE_INSTALL in
	   poller )
	       file="DiscoveryAgent_poller.py"
	       $SED -i -e 's|@KEY@|'"$key"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1	
	       ;;
	   central )
	       file="DiscoveryAgent_central.py"
	       $SED -i -e 's|@KEY@|'"$key"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1	
	       ;;
	   both )
	       file="DiscoveryAgent_poller.py"
	       $SED -i -e 's|@KEY@|'"$key"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1	
	       file="DiscoveryAgent_central.py"
	       $SED -i -e 's|@KEY@|'"$key"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1	
	       ;;
	   * )
	       ;;
       esac
       return 1
   fi
}


#----
## (Install init script on distrib)
##
## use this fonction to install a init script on your system
##    debian    update-rc.d
##    redhat    chkconfig
##    Suse      chkconfig
##    FreeBSD   add ${service}_enable=YES in /etc/rc.conf
##
## @param         name of service
## @return 0      install service ok
## @return 1      install service fail
#----
function install_init_service() {
    local service=$1
    if [ "$DISTRIB" = "DEBIAN" ] || [ "$DISTRIB" = "UBUNTU" ]; then
        update-rc.d $service start 99 2 3 4 5 . stop 30 0 1 6 . >> $LOG_FILE 2>&1
    elif [ "$DISTRIB" = "SUSE" ] ; then
        chkconfig --add $service  >> $LOG_FILE 2>&1
    elif [ "$DISTRIB" = "REDHAT"  ] || [ "DISTRIB" = "CENTOS" ]; then
# Just for CentOS :p bug #1148
      	if [ -x /sbin/chkconfig ] ; then
      	    /sbin/chkconfig --add $service >> $LOG_FILE 2>&1
      	else
            chkconfig --add $service >> $LOG_FILE 2>&1
      	fi
    elif [ "$DISTRIB" = "FREEBSD" ] ; then
        echo_info "You must configure your /etc/rc.conf with": ${service}
    else
	echo_faillure "Impossible to install your run level for " ${service} "$fail"
        return 1
    fi
    return 0
}

#----
## (Uninstall init script on distrib)
##
## use this fonction to uninstall a init script on your system
##    debian    update-rc.d
##    redhat    chkconfig
##    Suse      chkconfig
##    FreeBSD   add ${service}_enable=YES in /etc/rc.conf
##
## @param         name of service
## @return 0      uninstall service ok
## @return 1      uninstall service fail
#----
function uninstall_init_service() {
    local service=$1
    if [ "$DISTRIB" = "DEBIAN" ] || [ "$DISTRIB" = "UBUNTU" ]; then
        update-rc.d $service remove >> $LOG_FILE 2>&1
    elif [ "$DISTRIB" = "SUSE" ] ; then
        chkconfig --del $service  >> $LOG_FILE 2>&1
    elif [ "$DISTRIB" = "REDHAT"  ] || [ "DISTRIB" = "CENTOS" ]; then
# Just for CentOS :p bug #1148
      	if [ -x /sbin/chkconfig ] ; then
      	    /sbin/chkconfig --del $service >> $LOG_FILE 2>&1
      	else
            chkconfig --del $service >> $LOG_FILE 2>&1
      	fi
    elif [ "$DISTRIB" = "FREEBSD" ] ; then
        echo_info "You must configure your /etc/rc.conf with": ${service}
    else
	echo_faillure "Impossible to uninstall your run level for " ${service} "$fail"
        return 1
    fi
    return 0
}

#---
## {Install Init Discovery-agent}
##
## @Stdout Actions realised by function
## @Stderr Log into $LOG_FILE
#----
function install_init_discovery-agent() {
    if [ $UPDATE -eq 1 ]; then
	echo ""
        yes_no_default "Do you want to install discovery-agent run level ?" $yes
	if [ "$?" -eq 0 ] ; then
	    SCRIPT_START="0"
	    copy_init_discovery-agent;
	    echo -n "Creating init links"
	    install_init_service $SCRIPT_AGENT_INIT
	    display_return "$?" "Creating init links"
	    return 0
	else
	    SCRIPT_START="1"
	    echo "Don't forget to execute poller agent after each reboot/start machine :"
	    echo -e "\t$INIT_D/$SCRIPT_AGENT_INIT start"
	    return 1
	fi
   fi
}
	
#---
## {Install Discovery Module}
##
## @Stdout Actions realised by function
## @Stderr Log into $LOG_FILE
#----
function install_module() {
    local file=""
    write_header "Install Discovery Module" ""
    
    echo -n "Creating temp install directory"
    /bin/mkdir -p $TEMP_D >> $LOG_FILE 2>&1
    display_return "$?" "Creating temp install directory"
    /bin/cp -Rf $BASE_DIR/www/modules/Discovery/* $TEMP_D/ >> $LOG_FILE 2>&1
    /bin/rm -Rf $TEMP_D/install $TEMP_D/*.log >> $LOG_FILE 2>&1
    
    echo -n "Setting rights"
    ${CHMOD} -R 755 $TEMP_D/* >> $LOG_FILE 2>&1
    display_return "$?" "Setting rights"
    
    echo -n "Setting owner/group"
    ${CHOWN} -R $WEB_USER.$WEB_GROUP $TEMP_D/* >> $LOG_FILE 2>&1
    display_return "$?" "Setting owner/group"
    
    echo "Changing macro"
    file="include/update.php"
    echo -ne "\tfor update.php"
    $SED -i -e 's|@CENTREON_ETC@|'"$CENTREON_CONF"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    $SED -i -e 's|@AGENT_DIR@|'"$AGENT_DIR"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for update.php"
    file="include/verif_discovery_status.php"
    echo -ne "\tfor verif_discovery_status.php"
    $SED -i -e 's|@CENTREON_ETC@|'"$CENTREON_CONF"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for verif_discovery_status.php"
    file="include/ips.php"
    echo -ne "\tfor ips.php"
    $SED -i -e 's|@AGENT_DIR@|'"$AGENT_DIR"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for ips.php"
    file="include/results.php"
    echo -ne "\tfor results.php"
    $SED -i -e 's|@AGENT_DIR@|'"$AGENT_DIR"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for results.php"
    echo -ne "\tfor refresh_result.php"
    file="include/refresh_result.php"
    $SED -i -e 's|@CENTREON_ETC@|'"$CENTREON_CONF"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for refresh_result.php"
    file="sql/install.sql"
    echo -ne "\tfor install.sql"
    $SED -i -e 's|@DB_NAME_CENTREON@|'"$DB_NAME_CENTREON"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for install.sql"
    file="sql/uninstall.sql"
    echo -ne "\tfor uninstall.sql"
    $SED -i -e 's|@DB_NAME_CENTREON@|'"$DB_NAME_CENTREON"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for uninstall.sql"
    
    INSTALL_DIR_MODULE=$INSTALL_DIR_CENTREON/$MODULE_DIR
    
    if [ -d $INSTALL_DIR_MODULE ] && [ $UPDATE -eq 1 ] ; then
	if [ -d  $INSTALL_DIR_CENTREON/$BACKUP ] ; then
	    echo -n "Delete old Discovery backup"
	    /bin/rm -Rf $INSTALL_DIR_CENTREON/$BACKUP/* >> $LOG_FILE 2>&1
	    display_return "$?" "Delete old Discovery backup"
	else
	    echo -n "Create a directory to backup old files"
	    /bin/mkdir $INSTALL_DIR_CENTREON/$BACKUP >> $LOG_FILE 2>&1
	    display_return "$?" "Create a directory to backup old files"
	fi
	echo -n "Backup old installation"
	/bin/mv $INSTALL_DIR_MODULE/* $INSTALL_DIR_CENTREON/$BACKUP >> $LOG_FILE 2>&1
	display_return "$?" "Backup old installation"
    fi
    
    if [ ! -d $INSTALL_DIR_MODULE ] ; then
	echo -n "Create module directory"
	/bin/mkdir $INSTALL_DIR_MODULE >> $LOG_FILE 2>&1
	display_return "$?" "Create module directory"
	echo -n "Change owner on module directory"
	${CHOWN} -R $WEB_USER.$WEB_GROUP $INSTALL_DIR_MODULE >> $LOG_FILE 2>&1
	display_return "$?" "Change owner on module directory"
	echo -n "Change rights on module directory"
	${CHMOD} -R 755 $INSTALL_DIR_MODULE >> $LOG_FILE 2>&1
	display_return "$?" "Change rights on module directory"
    fi
    
    echo -n "Copying module"
    /bin/cp -Rf --preserve $TEMP_D/* $INSTALL_DIR_CENTREON/$MODULE_DIR >> $LOG_FILE 2>&1
    display_return "$?" "Copying module"
    
    echo -n "Delete temp install directory"
    /bin/rm -Rf $TEMP_D >> $LOG_FILE 2>&1
    display_return "$?" "Delete temp install directory"
}

#----
## {Install Discovery Agent}
##
## @Stdout Actions realised by function
## @Stderr Log into $LOG_FILE
#----
function install_agent() {
    local file=""
    write_header "Install Discovery Agent" ""

    echo -n "Creating temp install directory"
    TEMP_D="/tmp/Install_agent"
    /bin/mkdir -p $TEMP_D >> $LOG_FILE 2>&1
    display_return "$?" "Creating temp install directory"
    /bin/cp -Rf $BASE_DIR/agents/* $TEMP_D/ >> $LOG_FILE 2>&1
  
    if [ $UPDATE -eq 1 ]; then
	echo ""
	get_agent_install_directory_location;
    fi

    install_security_agent;

    echo -n "Setting rights"
    ${CHMOD} -R 755 $TEMP_D/* >> $LOG_FILE 2>&1
    display_return "$?" "Setting rights"
    
    echo -n "Setting owner/group"
    ${CHOWN} -R root:root $TEMP_D/* >> $LOG_FILE 2>&1
    display_return "$?" "Setting owner/group"
	
    if [ "$?" -eq 0 ] ; then
	if [ ! -d $AGENT_DIR ] ; then
	    echo -n "Creating the directory $AGENT_DIR"
	    /bin/mkdir -p $AGENT_DIR >> $LOG_FILE 2>&1
	    display_return "$?" "Creating the directory $AGENT_DIR"
	fi
        echo -ne "Changing macro for DiscoveryAgent_central.py"
        file="DiscoveryAgent_central.py"
        $SED -i -e 's|@CENTREON_ETC@|'"$CENTREON_CONF"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
        $SED -i -e 's|@AGENT_DIR@|'"$AGENT_DIR"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
        display_return "$?" "Changing macros for DiscoveryAgent_central.py"
        echo -ne "Changing macro for DiscoveryAgent_poller.py"
        file="DiscoveryAgent_poller.py"
        $SED -i -e 's|@AGENT_DIR@|'"$AGENT_DIR"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
        display_return "$?" "Changing macro for DiscoveryAgent_poller.py"
	
	echo -ne "Creating the log directory"
	/bin/mkdir -p $AGENT_DIR/log >> $LOG_FILE 2>&1
	display_return "$?" "Creating the log directory ($AGENT_DIR/log)"
	echo -ne "Setting rights"
	${CHOWN} -R $WEB_USER:$WEB_GROUP $AGENT_DIR/log >> $LOG_FILE 2>&1
	${CHMOD} -R 755 $AGENT_DIR/log >> $LOG_FILE 2>&1
	display_return "$?" "Setting rights"

	echo -n "Copy Discovery "
	case $TYPE_INSTALL in
	    poller )
		echo -n "poller agent"
	     	/bin/cp -Rf --preserve $TEMP_D/DiscoveryAgent_poller.py $AGENT_DIR >> $LOG_FILE 2>&1
		display_return "$?" "Copy Discovery poller agent"
		install_init_discovery-agent;
		execute_discovery-agent;
		;;
	    central )
		echo -n "central agent"
		/bin/cp -Rf --preserve $TEMP_D/DiscoveryAgent_central.py $AGENT_DIR >> $LOG_FILE 2>&1
		display_return "$?" "Copy Discovery central agent"
		;;
	    both )
		echo -n "poller and central agents"
		/bin/cp -Rf --preserve $TEMP_D/*.py $AGENT_DIR >> $LOG_FILE 2>&1
		display_return "$?" "Copy Discovery poller and central agents"
		install_init_discovery-agent;
		execute_discovery-agent;
		;;
	    * )
		;;
	esac

	echo -n "Delete temp install directory"
	/bin/rm -Rf $TEMP_D >> $LOG_FILE 2>&1
	display_return "$?" "Delete temp install directory"
	return 0
    else
	echo -n "Delete temp install directory"
	/bin/rm -Rf $TEMP_D >> $LOG_FILE 2>&1
	display_return "$?" "Delete temp install directory"
	return 1
    fi
}


######### OTHERS #########
    
#----
## (Execute discovery agent poller)
##
## execute $INIT_D/discovery-agent.sh
## @return 0      starting ok
## @return 1      starting ko
#----
function execute_discovery-agent() {
    local tmp=""
    
    if [ "$UPDATE" -eq 1 ]; then
	echo ""
	yes_no_default "Do you want to execute discovery poller agent now ?" $yes
	tmp=$?
    else
	tmp=$SCRIPT_START
    fi
    
    if [ "$tmp" -eq 0 ] ; then
	$INIT_D/$SCRIPT_AGENT_INIT status >> $LOG_FILE 2>&1			
	if [ "$?" -eq 0 ] ; then
	    echo -ne "Restarting discovery agent" 
	    $INIT_D/$SCRIPT_AGENT_INIT restart >> $LOG_FILE 2>&1
	    display_return "$?" "Restarting discovery agent"
	else
	    echo -ne "Starting discovery agent"
	    $INIT_D/$SCRIPT_AGENT_INIT start >> $LOG_FILE 2>&1
	    display_return "$?" "Starting discovery agent"
	fi
	return 0			
    else  
	echo "Don't forget to execute poller agent at installation end :"
	echo -e "\t$INIT_D/$SCRIPT_AGENT_INIT start"
	return 1
    fi
}
#----
## (Define OS)
##
## define your distribution from lsb_release command
##    Debian
##    Suse
##    Redhat
##    FreeBSD
##
## @return 0      OS found
## @return 1      OS not found
#----
function find_OS() {
    local system=""
    local lsb_release=""
    system="$(uname -s)"
    if [ "$system" = "Linux" ] ; then
        if [ "$(lsb_release > /dev/null 2>&1; echo $?)" -eq "0" ] ; then
            lsb_release="$(lsb_release -i -s)"
        else
            lsb_release="NOT_FOUND"
        fi
        if [ "$lsb_release" = "Debian" ] || [ -e "/etc/debian_version" ] ; then 
            DISTRIB="DEBIAN"
            log "INFO" "$(gettext "GNU/Linux Debian Distribution")"
	elif [ "$lsb_release" = "Ubuntu" ] ; then
	    DISTRIB="UBUNTU"
            log "INFO" "$(gettext "GNU/Linux Ubuntu Distribution")"
	elif [ "$lsb_release" = "CentOS" ] ; then
            DISTRIB="CENTOS"
            log "INFO" "$(gettext "GNU/Linux CentOS Distribution")"
        elif [ "$lsb_release" = "RedHatEnterpriseES" ] || [ -e "/etc/redhat-release" ] ; then
            DISTRIB="REDHAT"
            log "INFO" "$(gettext "GNU/Linux Redhat Distribution")"
	elif [ "$lsb_release" = "Fedora" ] ; then
	    DISTRIB="FEDORA"
            log "INFO" "$(gettext "GNU/Linux Fedora Distribution")"
        else
            DISTRIB="NOT_FOUND"
            log "INFO" "$(gettext "GNU/Linux distribution not found")"
            return 1
        fi
    elif [ "$system" = "FreeBSD" ] ; then
        DISTRIB="FREEBSD"
        log "INFO" "$(gettext "FreeBSD System")"
    elif [ "$system" = "AIX" ] ; then
        DISTRIB="AIX"
        log "INFO" "$(gettext "AIX System")"
    elif [ "$system" = "SunOS" ] ; then
        DISTRIB="SUNOS"
        log "INFO" "$(gettext "SunOS System")"
    else
        DISTRIB="NOT_FOUND"
        log "INFO" "$(gettext "System not found")"
    fi
    return 0
}

#---
## (Check package)
##
## @param1        package to test
## @return 0      packages found
## @return 1      packages not found
#---
function check_package() {
    if [ "$DISTRIB" == "DEBIAN" ] || [ "$DISTRIB" == "UBUNTU" ] ; then
	return `${DPKG} -l | grep $1 | wc -l`
    elif [ "$DISTRIB" == "REDHAT" ] || [ "$DISTRIB" == "CENTOS" ] ; then
	return `${YUM} list installed | grep $1 | wc -l`
    fi
}

#----
## check the minimum version number for a binary
## @param1      binary to check
## @param2      major number version minimum
## @param3      minor number version minimum
## @return 0    ok
## @return 1    ko
## @Globals     PATH
#----
function check_min_version() {
#    pathfind_ret $1 $1
#    echo -e "\n\tchemin : $1"
    if [ "$?" -ne 0 ] ; then
	return 255
    else
	output=$($1 -V 2>&1)
	major=$(echo $output | cut -f1 -d '.' | sed 's/[^0-9]//g')
#	echo "output : $output"
#	echo "para 2 : $2"
#	echo "para 3 : $3"
#	echo "major : $major"

	if [ $major -ge $2 ]; then
	    minor=$(echo $output | cut -f2 -d '.' | sed 's/[^0-9]//g')
#	    echo "output : $output"
#	    echo "para 2 : $2"
#	    echo "para 3 : $3"
#	    echo "minor : $minor"

	    if [ $minor -lt $3 ] ; then
		return 1
	    fi
	    return 0
	else
	    return 1
	fi
    fi
}

#---
## (Check version)
##
## @param1        file to read with version numbers
## @return 0      ok for all binaries
## @return 1      ko for at least a binary
#---
function check_version(){
    local pgm major_min minor_min major minor type_install
    local error=0 result
    while read ligne
    do
        if [ -n "${ligne:0:1}" ] && [ "${ligne:0:1}" != '#' ] ; then
	    type_install=$(echo $ligne | cut -f1 -d "=")
            pgm=$(echo $ligne | cut -f2 -d "=")
            major_min=$(echo $ligne | cut -f3 -d "=")
            minor_min=$(echo $ligne | cut -f4 -d "=")
	    if [ -z $minor_min ] ; then
		minor_min="0"
	    fi
	    if [ "$type_install" == "$TYPE_INSTALL" ] ; then
		echo -ne "$pgm"
		check_min_version $pgm $major_min $minor_min
		result=$?
		echo -ne "\t\t\t\t$major.$minor\t(min. $major_min.$minor_min)"
		if [ $result -eq 0 ] ; then
		    display_return "0" "$pgm (min. $major_min.$minor_min)"
		else
		    display_return "1" "$pgm (min. $major_min.$minor_min)"
		    error=1
		fi
	    fi
	fi
    done < $1
    if [ $error == 1 ]; then
	echo_info "\nPlease check fail version number and retry"
	exit 1
    fi
}


#----
## (Copy start/stop script in the /etc/init.d directory)
##
## @return 0      copy script ok
## @return 1      copy script fail || don't overwrite
#----
function copy_init_discovery-agent() {
    local file=""
    ${CHOWN} root:root $TEMP_D/$SCRIPT_AGENT_INIT >> $LOG_FILE 2>&1
    ${CHMOD} 755 $TEMP_D/$SCRIPT_AGENT_INIT >> $LOG_FILE 2>&1
    echo -n "Changing macro for init script"
    file="$SCRIPT_AGENT_INIT"
    $SED -i -e 's|@AGENT_DIR@|'"$AGENT_DIR"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for init script"
    
    if [ -f $INIT_D/$SCRIPT_AGENT_INIT ] ; then
	echo ""
	yes_no_default "The script exists. Do you want to overwrite it?"
        if [ "$?" -eq 1 ] ; then
	    return 1
        fi
    fi
    echo -n "Copying init script"
    cp $TEMP_D/$SCRIPT_AGENT_INIT $INIT_D >> $LOG_FILE 2>&1
    display_return "$?" "Copying init script"
    return $?
}

#---
## (Check old install)
##
## @return 0      install exists
## @return 1      install doesn t exist
#---
function check_old_install(){
    local temp="" file="" update_version="" major_update_version="" minor_update_version=""
    
    write_header "Detect previous installation"

    if [ -f $DIR_CONF_DISCO/$FILE_CONF_DISCO ] && [ `grep "# Discovery version" $DIR_CONF_DISCO/$FILE_CONF_DISCO | wc -l` -eq 1 ] ; then
	update_version=$(grep "# Discovery version" $DIR_CONF_DISCO/$FILE_CONF_DISCO | cut -d " " -f4)
	major_update_version=$(echo $update_version | cut -d "." -f1)
	minor_update_version=$(echo $update_version | cut -d "." -f2)
	#check install.sh version is more recent than instCentDisco.conf
	if [ $major_update_version -le `echo $VERSION | cut -d "." -f1` ] && [ $minor_update_version -le `echo $VERSION | cut -d "." -f2` ] ; then
	    echo_success "Finding configuration in: $DIR_CONF_DISCO" "$ok"
	    echo -e "\nYou seem to have an existing Discovery install."
	else
	    echo_failure "The configuration file (version $major_update_version.$minor_update_version) was created for another more recent version. The install script version is $VERSION" "$fail"
	exit 1;
	fi
   else
	echo_failure "Finding configuration file in: $DIR_CONF_DISCO" "$fail"
	exit 1;
    fi
    yes_no_default "Do you want to use the previous Discovery install parameters ?" $yes
    if [ "$?" -ne 0 ] ; then
	echo -e "\nYou need to remove the current install. Execute install script with \"-r\" parameter and then execute it again with \"-i\" parameter for a new fresh install ;-)"
	exit 1;
    else
	return 0;
    fi
}

#---
## (Execute SQL script)
##
## @param1        SQL script
## @return 0      ok
## @return 1      ko
#---
function execute_sql(){
    local db_login=`${CAT} $CENTREON_CONF/$FILE_CONF_CENT | grep "\$conf_centreon\['user'\]" | cut -d '=' -f2 | ${SED} -e s/\"//g -e s/\ //g -e s/\;//g`
    local db_pass=`${CAT} $CENTREON_CONF/$FILE_CONF_CENT | grep "\$conf_centreon\['password'\]" | cut -d '=' -f2 | ${SED} -e s/\"//g -e s/\ //g -e s/\;//g`

    mysql -u $db_login -p$db_pass $DB_NAME_CENTREON < $1 >> $LOG_FILE 2>&1
    return $?
}

#---
## (Execute SQL script for update)
##
## @param1        SQL script
## @return 0      always
#---
function execute_sql_update(){
    local file=""
#    INSTALL_DIR_MODULE=$INSTALL_DIR_CENTREON/$MODULE_DIR
    
    write_header "Execute SQL scripts"

    echo -n "Creating temp install directory"
    /bin/mkdir -p $TEMP_D >> $LOG_FILE 2>&1
    display_return "$?" "Creating temp install directory"
    
    echo "Changing macro"
    file="update.sql"
    echo -ne "\tfor $file"
    # update.sql from new install
    /bin/cp -Rf $INSTALL_DIR/$file $TEMP_D/ >>$LOG_FILE 2>&1
    $SED -i -e 's|@VERSION@|'"$VERSION"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for $file"

    file="install.sql"
    echo -ne "\tfor $file"
    # install.sql from new install
    /bin/cp -Rf $BASE_DIR/www/modules/Discovery/sql/$file* $TEMP_D/ >> $LOG_FILE 2>&1
    $SED -i -e 's|@DB_NAME_CENTREON@|'"$DB_NAME_CENTREON"'|g' $TEMP_D/$file >> $LOG_FILE 2>&1
    display_return "$?" "Changing macro for $file"
    # uninstall.sql from old install
    file="uninstall.sql"
    echo -n "Executing old $file"
    execute_sql "$INSTALL_DIR_CENTREON/$MODULE_DIR/sql/$file"
    display_return "$?" "Executing old $file"
    # install.sql from new install
    file="install.sql"
    echo -n "Executing $file"
    execute_sql "$TEMP_D/$file"
    display_return "$?" "Executing $file"
    # update.sql from new install
    file="update.sql"
    echo -n "Executing $file"
    execute_sql "$TEMP_D/$file"
    display_return "$?" "Executing $file"

    /bin/rm -Rf $TEMP_D >> $LOG_FILE 2>&1
    return 0
}

#---
## (Create instCentDisco.conf file)
##
## @return 0      always
#---
function create_CentDiscoConf(){
#    write_header "Create CentDiscoConf file"
    echo "Creating CentDiscoConf file" >> $LOG_FILE
    if [ -f $AGENT_DIR/$FILE_CONF_DISCO ] ; then
	/bin/mv $AGENT_DIR/$FILE_CONF_DISCO $AGENT_DIR/$FILE_CONF_DISCO.old >> $LOG_FILE 2>&1
    fi
    echo "# Discovery version $VERSION" >> $AGENT_DIR/$FILE_CONF_DISCO
    echo "# `date`" >> $AGENT_DIR/$FILE_CONF_DISCO
    echo "AGENT_DIR=$AGENT_DIR" >> $AGENT_DIR/$FILE_CONF_DISCO
    echo "CENTREON_CONF=$CENTREON_CONF" >> $AGENT_DIR/$FILE_CONF_DISCO
    echo "TYPE_INSTALL=$TYPE_INSTALL" >> $AGENT_DIR/$FILE_CONF_DISCO
    echo "SECURE=$SECURE" >> $AGENT_DIR/$FILE_CONF_DISCO
    echo "KEY=$KEY" >> $AGENT_DIR/$FILE_CONF_DISCO
    echo "SCRIPT_START=$SCRIPT_START" >> $AGENT_DIR/$FILE_CONF_DISCO
    return 0
}

#---
## (Check list packages)
##
## @return 0      if all packages found
## @return 1      if at least package not found
#---
function check_list_packages(){
    local error=0 package=""

    write_header "Checking all needed packages" ""
    for package in $PACKAGES; do
        echo -n $package
        check_package $package;
        if [ $? -eq 0 ] ; then
        #package not installed !
	    display_return "1" "$package"
	    error=1
        else
        #package installed !
	    display_return "0" "$package"
        fi
    done
    if [ $error == 1 ]; then
        echo_info "\nPlease check fail packages and retry"
        exit 1
    fi
}

#---
## (Delete all files' module)
##
## @return 0      suppression ok
## @return 1      suppression ko
#---
function delete_module(){
    if [ $TYPE_INSTALL != "poller" ] ; then
	echo -ne "Executing uninstall.sql"
	execute_sql "$INSTALL_DIR_CENTREON/$MODULE_DIR/sql/uninstall.sql"
	display_return "$?" "Executing uninstall.sql"
	echo -n "Executing remove_module.sql"
	execute_sql "$INSTALL_DIR/remove_module.sql"
	display_return "$?" "Executing remove_module.sql"
	echo -ne "Deleting Discovery module directory"
	/bin/rm -Rf $INSTALL_DIR_CENTREON/$MODULE_DIR >> $LOG_FILE 2>&1
	display_return "$?" "Deleting Discovery module directory"
	delete_backup_discovery;
    fi
    
    if [ $TYPE_INSTALL != "central" ] ; then
	echo -ne "Stopping discovery agent"
	$INIT_D/$SCRIPT_AGENT_INIT stop >> $LOG_FILE 2>&1
	display_return "$?" "Stopping discovery agent"
	echo -ne "Deleting init links"
	uninstall_init_service $SCRIPT_AGENT_INIT >> $LOG_FILE 2>&1
	display_return "$?" "Deleting init links"
	echo -ne "Deleting init script"
	/bin/rm -Rf $INIT_D/$SCRIPT_AGENT_INIT >> $LOG_FILE	2>&1
	display_return "$?" "Deleting init script"
    fi
    echo -ne "Deleting Discovery agent directory"
    /bin/rm -Rf $AGENT_DIR >> $LOG_FILE 2>&1
    display_return "$?" "Deleting Discovery agent directory"
}

#---
## (Delete backup Discovery module directory)
##
## @return 0      suppression ok
## @return 1      suppression ko
#---
function delete_backup_discovery(){
    if [ -d  $INSTALL_DIR_CENTREON/$BACKUP ] ; then
	echo ""
	yes_no_default "Do you want to delete Discovery module backup directory ?" $yes
	if [ "$?" -eq 0 ] ; then
	    echo -n "Deleting Discovery module backup directory"
	    /bin/rm -Rf $INSTALL_DIR_CENTREON/$BACKUP >> $LOG_FILE 2>&1
	    display_return "$?" "Deleting Discovery module backup directory"
	else
	    echo_info "\nThe $INSTALL_DIR_CENTREON/$BACKUP doesn't delete"
	fi
    fi
}
