#!/bin/bash 

# This file is part of Centreon-Discovery module.
#
# Centreon-Discovery is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses>.
#
# Module name: Centreon-Discovery
#
# First developpement by: Jean Marc Grisard - Christophe Coraboeuf
# Adaptation for Centreon 2.0 by: Merethis team
# Inspired from Watt's script.
#
# Modified by Sub2.13
#
# WEBSITE: http://community.centreon.com/projects/centreon-discovery
# SVN: http://svn.modules.centreon.com/centreon-discovery

#---------------------#
# Used by install.sh  #
#---------------------#

# Define Discovery version
NAME="Discovery"
VERSION="2.1.1"
MODULE=$NAME.$VERSION

# Global vars
LOG_VERSION="Centreon Module $MODULE installation"
FILE_CONF="instCentWeb.conf"
FILE_CONF_CENT="centreon.conf.php"
FILE_CONF_CENTPLUGIN="instCentPlugins.conf"
CENTREON_CONF="/etc/centreon"
AGENT_DIR="/usr/share/centreon-discovery"
MODULE_DIR="www/modules/Discovery"
INSTALL_DIR_CENTREON=""
WEB_USER=""
WEB_GROUP=""
NAGIOS_USER=""
NAGIOS_GROUP=""
NAGIOS_PLUGIN=""
DB_NAME_CENTREON=""
BACKUP="www/modules/Discovery_backup"
INIT_D="/etc/init.d"
PWD=`pwd`
TEMP=/tmp/install.$$
_tmp_install_opts="0"
silent_install="0"
DISTRIB=""
TYPE_INSTALL=""
SCRIPT_AGENT_INIT="centreon-discovery.sh"

BINARIES="rm cp mv ${CHMOD} ${CHOWN} echo more mkdir find ${GREP} ${CAT} ${SED} ${PYTHON} ${GCC}"

## Vars
yes="y"
no="n"
ok="OK"
fail="FAIL"
passed="PASSED"
warning="WARNING"
critical="CRITICAL"

line="------------------------------------------------------------------------"

# Init binary to empty to use pathfind or manual define
GREP=""
CAT=""
SED=""
CHMOD=""
CHOWN=""

## COLOR FUNCTIONS
RES_COL="60"
MOVE_TO_COL="\\033[${RES_COL}G"
SETCOLOR_INFO="\\033[1;38m"
SETCOLOR_SUCCESS="\\033[1;32m"
SETCOLOR_FAILURE="\\033[1;31m"
SETCOLOR_WARNING="\\033[1;33m"
SETCOLOR_NORMAL="\\033[0;39m"


#INSTALL_DIR="$BASE_DIR/install"
#export INSTALL_DIR

#export line